// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ1e6tJ_R3tFG8SySo9fW5LO7sRg-zL5c',
    appId: '1:51413225902:web:28758f8ed9696cd6d0383f',
    messagingSenderId: '51413225902',
    projectId: 'todo-ced57',
    authDomain: 'todo-ced57.firebaseapp.com',
    storageBucket: 'todo-ced57.appspot.com',
    measurementId: 'G-44KK25RVHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4cqAeGT4w_D8gn0b5t_RzYQNeByfJbAg',
    appId: '1:51413225902:android:324dcee75c37f427d0383f',
    messagingSenderId: '51413225902',
    projectId: 'todo-ced57',
    storageBucket: 'todo-ced57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUUi403vK7aP5-eTaum3EtyE6VJZWDxyY',
    appId: '1:51413225902:ios:2d32c28636fc9755d0383f',
    messagingSenderId: '51413225902',
    projectId: 'todo-ced57',
    storageBucket: 'todo-ced57.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUUi403vK7aP5-eTaum3EtyE6VJZWDxyY',
    appId: '1:51413225902:ios:2d32c28636fc9755d0383f',
    messagingSenderId: '51413225902',
    projectId: 'todo-ced57',
    storageBucket: 'todo-ced57.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZ1e6tJ_R3tFG8SySo9fW5LO7sRg-zL5c',
    appId: '1:51413225902:web:aa2efcfa35446ee9d0383f',
    messagingSenderId: '51413225902',
    projectId: 'todo-ced57',
    authDomain: 'todo-ced57.firebaseapp.com',
    storageBucket: 'todo-ced57.appspot.com',
    measurementId: 'G-JB284CKM71',
  );
}
